"""empty message

Revision ID: 284febcf7fcf
Revises: 3fa98845fc5d
Create Date: 2020-04-16 18:53:45.524469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284febcf7fcf'
down_revision = '3fa98845fc5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_path', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_user_avatar_path'), 'user', ['avatar_path'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_avatar_path'), table_name='user')
    op.drop_column('user', 'avatar_path')
    # ### end Alembic commands ###
