"""empty message

Revision ID: 79680f630216
Revises: 43cd9c79425b
Create Date: 2019-09-22 20:51:43.033309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79680f630216'
down_revision = '43cd9c79425b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
