"""empty message

Revision ID: ac50b5928de2
Revises: 79680f630216
Create Date: 2019-10-04 10:29:00.723773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac50b5928de2'
down_revision = '79680f630216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('facebook_id', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_user_facebook_id'), 'user', ['facebook_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_facebook_id'), table_name='user')
    op.drop_column('user', 'facebook_id')
    # ### end Alembic commands ###
